# dockerfile for frontend
FROM nginx

RUN apt-get update
RUN apt-get install procps net-tools -y
RUN rm /etc/nginx/conf.d/default.conf
COPY nginxconfig.conf /etc/nginx/conf.d/
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

